
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'TEXT ID LPAREN RPAREN QUOTES COMMA COLON document : txt  txt : id_init  txt : command  txt : txt id_init  txt : txt command  id_init : ID LPAREN text_param COMMA text_param RPAREN  text_param : QUOTES TEXT QUOTES  command : TEXT LPAREN ID COMMA ID COMMA jump_param RPAREN  jump_param : TEXT COLON TEXT command : TEXT LPAREN ID RPAREN  command : TEXT LPAREN ID COMMA ID RPAREN  command : TEXT LPAREN ID COMMA ID COMMA ID RPAREN '
    
_lr_action_items = {'ID':([0,2,3,4,7,8,10,16,17,21,22,23,28,29,],[5,5,-2,-3,-4,-5,13,20,-10,-6,25,-11,-12,-8,]),'TEXT':([0,2,3,4,7,8,12,17,21,22,23,27,28,29,],[6,6,-2,-3,-4,-5,15,-10,-6,24,-11,30,-12,-8,]),'$end':([1,2,3,4,7,8,17,21,23,28,29,],[0,-1,-2,-3,-4,-5,-10,-6,-11,-12,-8,]),'LPAREN':([5,6,],[9,10,]),'QUOTES':([9,14,15,],[12,12,19,]),'COMMA':([11,13,19,20,],[14,16,-7,22,]),'RPAREN':([13,18,19,20,25,26,30,],[17,21,-7,23,28,29,-9,]),'COLON':([24,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'txt':([0,],[2,]),'id_init':([0,2,],[3,7,]),'command':([0,2,],[4,8,]),'text_param':([9,14,],[11,18,]),'jump_param':([22,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> txt','document',1,'p_document','parse.py',52),
  ('txt -> id_init','txt',1,'p_txt_id','parse.py',57),
  ('txt -> command','txt',1,'p_txt_command','parse.py',62),
  ('txt -> txt id_init','txt',2,'p_txt_many_ids','parse.py',66),
  ('txt -> txt command','txt',2,'p_txt_many_commands','parse.py',70),
  ('id_init -> ID LPAREN text_param COMMA text_param RPAREN','id_init',6,'p_id_init','parse.py',74),
  ('text_param -> QUOTES TEXT QUOTES','text_param',3,'p_text_param','parse.py',80),
  ('command -> TEXT LPAREN ID COMMA ID COMMA jump_param RPAREN','command',8,'p_command_jump','parse.py',85),
  ('jump_param -> TEXT COLON TEXT','jump_param',3,'p_jump_param','parse.py',98),
  ('command -> TEXT LPAREN ID RPAREN','command',4,'p_command_one_param','parse.py',103),
  ('command -> TEXT LPAREN ID COMMA ID RPAREN','command',6,'p_command_two_params','parse.py',116),
  ('command -> TEXT LPAREN ID COMMA ID COMMA ID RPAREN','command',8,'p_command_thee_params','parse.py',128),
]
